# Generated by Django 4.2.5 on 2023-09-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.AddField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='xml_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
