# Generated by Django 4.2.5 on 2023-09-17 21:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_job_job_id_job_id_job_xml_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reference_id',
            field=models.CharField(default=core.models.create_reference_id, max_length=16, unique=True),
        ),
    ]
