# Generated by Django 4.2.5 on 2023-09-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_reference_id'),
        ('core', 'unique_reference_id'),
    ]

    operations = [
    ]
