# Generated by Django 4.2.5 on 2023-09-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_0003_job_reference_id_unique_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='xmls/'),
        ),
        migrations.AddField(
            model_name='company',
            name='xml_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
