# Generated by Django 4.2.5 on 2023-09-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_xml_file_company_xml_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='xml_file_name',
        ),
    ]
